port: 7693
socks-port: 7695
allow-lan: true
mode: rule
log-level: error
external-controller: :9393
# secret: "980123XiopP!Pll23-"
cfw-latency-timeout: 1000
sniffing: true
ipv6: false

mitm-port: 7894
# Man-In-The-Middle attack
mitm:
  hosts: # use for others proxy type. E.g: TUN, socks
    - +.facebook.com
    - facebook.com
    # - +.fbcdn.net
    - app.perplaystudio.com
  rules: # rewrite rules
    # - '^https?://static\.xx\.fbcdn\.net/rsrc.php.* url reject-img'
    # - '^https?://www\.baidu\.com/ url reject-img'
    # - '^https?://www\.facebook\.com/1 url reject' # The "reject" returns HTTP status code 404 with no content.
    # - '^https?://www\.facebook\.com/2 url reject-200' # The "reject-200" returns HTTP status code 200 with no content.
    # - '^https?://www\.facebook\.com/3 url reject-img' # The "reject-img" returns HTTP status code 200 with content of 1px png.
    # - '^https?://www\.facebook\.com/4 url reject-dict' # The "reject-dict" returns HTTP status code 200 with content of empty json object.
    # - '^https?://www\.facebook\.com/5 url reject-array' # The "reject-array" returns HTTP status code 200 with content of empty json array.
    # - '^https?://www\.facebook\.com/(6) url 302 https://www.facebook.com/new-$1'
    # - '^https?://www\.(facebook)\.com/7 url 307 https://www.$1.com/new-7'
    # - '^https?://www\.facebook\.com/8 url request-header (\r\n)User-Agent:.+(\r\n) request-header $1User-Agent: haha-wriohoh$2' # The "request-header" works for all the http headers not just one single header, so you can match two or more headers including CRLF in one regular expression.
    # - '^https?://www\.facebook\.com/9 url request-body "pos_2":\[.*\],"pos_3" request-body "pos_2":[{"xx": "xx"}],"pos_3"'
    # - '^https?://www\.facebook\.com/10 url response-header (\r\n)Tracecode:.+(\r\n) response-header $1Tracecode: 88888888888$2'
    # - '^https?://www\.facebook\.com/11 url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'
    - '^https?://adsmanager-graph\.facebook\.com/.*/am_tabular url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'
    - '^https?://adsmanager-graph\.facebook\.com/.*/ads_reporting url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'
    - '^https?://adsmanager\.facebook\.com/adsmanager/manage/(campaigns|adsets|ads) url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'
    - '^https?://adsmanager\.facebook\.com/adsmanager/reporting/business_view url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'
    - '^https?://adsmanager\.facebook\.com/adsmanager/reporting/view url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'
    - '^https?://adsmanager-graph\.facebook\.com/.*/reporting url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'
    - '^https?://app\.perplaystudio\.com/fb.html url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'

# interface-name: en0
tun:
  enable: true
  stack: system #gvisor
  dns-hijack:
    - 0.0.0.0:53 #本地的dns设置为 223.6.6.6 和 8.8.8.8，不要用网关dns，会被跳过
  auto-route: true
  auto-detect-interface: true

# tproxy for linux
# tproxy-port: 9898
# iptables:
#   enable: true # default is false
#   inbound-interface: eth0 # detect the inbound interface, default is 'lo'

hosts:
  "code.nxit.us": "192.168.155.12"

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:8053
  enhanced-mode: redir-host
  # enhanced-mode: redir-host # 或 fake-ip
  # # fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  use-hosts: true
  default-nameserver:
    - 119.29.29.29
    - 114.114.114.114
  nameserver:
    # - 192.168.158.1
    # - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29

  fallback:
    # - tls://dns.google#DNS节点
    # - https://dns.rubyfish.cn/dns-query
    # - https://dns.pub/dns-query
    # - tcp://1.1.1.1
    - https://1.1.1.1/dns-query#DNS节点
    - https://dns.google/dns-query#DNS节点
  fallback-filter:
    geoip: false
    geosite:
      - gfw
    ipcidr:
      - 0.0.0.0/32
    domain:
      - "+.google.com"
      - "youtube.com"
      - "youtu.be"
      - "+.youtu.be"
      - "+.youtube.com"
      - "+.appspot.com"
      - "+.telegram.com"
      - "+.facebook.com"
      - "+.twitter.com"
      - "+.blogger.com"
      - "+.gmail.com"
      - "+.ytimg.com"
      - "+.gvt1.com"
      - "+.github.com"
      - "+.githubusercontent.com"
      - "+.gstatic.com"
      - "+.google-analytics.com"
      - "+.googletagmanager.com"
      - "cdn.ampproject.org"
      - "+.googleapis.com"
      - "+.google-analytics.com"
      - "+.gvt2.com"
      - "+.googlevideo.com"
      - "+.googleadservices.com"
      - "+.googlesyndication.com"
      - "+.doubleclick.net"
      - "+.fbcdn.net"

proxies:
- name: s-us3
  server: s2.apphaodian.com
  port: 32689
  type: trojan
  password: "exXnbm!23Ab0oK"
  udp: true
  network: tcp
  flow: "xtls-rprx-direct"
  sni: us3.akdfj.com
  timeout: 450
  max-fail: 2
  forbid-duration: 900
- name: s-ssg01
  server: s2.apphaodian.com
  port: 32689
  type: trojan
  password: "exXnbm!23Ab0oK"
  udp: true
  network: tcp
  flow: "xtls-rprx-direct"
  sni: ssg01.akdfj.com
  timeout: 450
  max-fail: 2
  forbid-duration: 900
- name: us3
  server: us3.apphaodian.com
  type: vless
  port: 443
  udp: true
  uuid: 333cbe20-6cd3-4d85-bffe-94f39e368574
  flow: xtls-rprx-vision
  tls: true
  servername: securemvt.apple.com
  alpn:
    - h2
    - http/1.1
  client-fingerprint: chrome
  skip-cert-verify: false
  reality-opts:
    public-key: 03vnAABj2L7w181ntEc3GsFZeN8USvJc1Js3SV7cSQ0
    short-id: 8f5e381c5eb38a09
  network: tcp
  smux:
    enabled: false
- name: hkt2
  server: hk01.apphaodian.com
  type: vless
  port: 443
  udp: true
  uuid: 333cbe20-6cd3-4d85-bffe-94f39e368574
  flow: xtls-rprx-vision
  tls: true
  servername: swcdn.apple.com
  alpn:
    - h2
    - http/1.1
  client-fingerprint: chrome
  skip-cert-verify: false
  reality-opts:
    public-key: 03vnAABj2L7w181ntEc3GsFZeN8USvJc1Js3SV7cSQ0
    short-id: 8f5e381c5eb38a09
  network: tcp
  smux:
    enabled: false
- name: 'hkt5-sg01'
  type: vless
  server: hkt5.apphaodian.com
  port: 443
  udp: true
  uuid: 333cbe20-6cd3-4d85-bffe-94f39e368574
  flow: xtls-rprx-vision
  tls: true
  servername: sfss.cdn-apple.com
  alpn:
    - h2
    - http/1.1
  client-fingerprint: chrome
  skip-cert-verify: false
  reality-opts:
    public-key: 03vnAABj2L7w181ntEc3GsFZeN8USvJc1Js3SV7cSQ0
    short-id: 8f5e381c5eb38a09
  network: tcp
  smux:
    enabled: false
- name: home-best
  server: git.utmcus.cn
  port: 52008
  type: ss
  cipher: aes-128-gcm
  password: fishGylK111111
  udp: true

proxy-groups:
  - name: 🔰 节点选择
    type: select
    disable-udp: false
    auto-backup: true
    lazy: false
    url: 'https://www.gstatic.com/generate_204'
    interval: 121
    proxies:
      - ♻️ 最快节点
      - home-best
      - hkt2
      - us3
      - s-us3
      - s-ssg01
      - hkt5-sg01
      - 香港卡选这个
  - name: ♻️ 最快节点
    type: url-test
    disable-udp: false
    url: 'https://www.gstatic.com/generate_204'
    interval: 61
    tolerance: 55
    proxies:
      - home-best
      - hkt2
      - us3
      - s-us3
      - s-ssg01
      - hkt5-sg01
      - 香港卡选这个
  - name: 香港卡选这个
    type: select
    proxies:
      - DIRECT
  - name: DNS节点
    type: select
    auto-backup: true
    proxies:
      - 🔰 节点选择
      - s-ssg01
      - s-us3
      - us3
      - hkt2
      - DIRECT

rules:
  - GEOIP,CN,香港卡选这个,no-resolve
  - MATCH,🔰 节点选择
  