# 广告系列、广告组、广告数据配置
accounts:
  "2084651242304060": # 这是户的id
    "120238882903790644": # 这可以是广告系列id、广告组id、广告id
      mark: "广告系列-a1-03" # 自己备注的名字，方便对应
      spent: "103.00" # 已花费
      reach: "103" # 覆盖人数
      impression: "1003" # 展示次数
    "120238820011380644":
      mark: "广告系列-1组-02"
      spent: "10015.00" # 已花费
      reach: "1015" # 覆盖人数
      impression: "1016" # 展示次数
    "120238883031710644":
      spent: "10000.00" # 已花费
      reach: "1000" # 覆盖人数
      impression: "10001" # 展示次数
    "120238882903770644":
      mark: "广告系列-1组-02-新销量广告组-新销量广告"
      spent: "1509.00" # 已花费
      reach: "1007" # 覆盖人数
      impression: "3007" # 展示次数
    "120238820011370644":
      mark: "广告系列-1组-02-新销量广告组-新销量广告"
      spent: "644.00" # 已花费
      reach: "644" # 覆盖人数
      impression: "3007" # 展示次数
    "120238820223920644":
      spent: "6442.00" # 已花费
      reach: "6442" # 覆盖人数
      impression: "3007" # 展示次数
    "120238820011390644":
      mark: "广告系列-1组-02-新销量广告组"
      spent: "7891.00" # 已花费
      reach: "3568" # 覆盖人数
      impression: "3007" # 展示次数
    "120238882903780644":
      mark: "a1-03-新销量广告组"
      spent: "7893.00" # 已花费
      reach: "3563" # 覆盖人数
      impression: "3003" # 展示次数
